apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: InfluxDB
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    httpMethod: POST
    url: http://MYPROMHOST:9090
    isDefault: 1
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    httpMethod: POST
    url: http://MYLOKIHOST:3100
    isDefault: 0
    version: 1
    editable: true
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: INFLUXDATABASE
    orgId: 1
    httpMethod: POST
    url: http://MYINFLUXHOST:8086
    jsonData:
      httpMode: GET
    isDefault: 0
    version: 1
    editable: true
