apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    httpMethod: POST
    url: http://127.0.0.1:9090
    isDefault: 1
    version: 1
    editable: false
