global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'consul_registered_services'
    metrics_path: '/metrics'
    consul_sd_configs:
    - server: 'localhost:8500'
      services: ["node-exporter", "nomad", "consul", "vault"]
    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app
    - source_labels: [__meta_consul_tags]
      regex: .*,_service=([^,]+),.*
      replacement: ${1}
      target_label: _service
    - source_labels: [__meta_consul_tags]
      regex: .*,_hostname=([^,]+),.*
      replacement: ${1}
      target_label: _hostname
    - source_labels: [__meta_consul_tags]
      regex: .*,_datacenter=([^,]+),.*
      replacement: ${1}
      target_label: _datacenter
  - job_name: 'vault'
    metrics_path: "/v1/sys/metrics"
    params:
      format: ['prometheus']
    scheme: https
    tls_config:
      ca_file: /mnt/certs/metricsca.pem
    bearer_token_file: /root/login.token
    static_configs:
    - targets: ['your_vault_server_here:8200']